AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - "Rakefile"
    - "anycablebility.gemspec"
  Exclude:
    - 'bin/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Style/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
